import fs from 'fs';
import path from 'path';
import util from 'util';
import { exec } from 'child_process';
import { CMSModulePlugin, InstallContext } from '../../pluginLoader';
import { runtimeManager } from '../../../services/runtimeManager';

const execPromise = util.promisify(exec);

const wordpressPlugin: CMSModulePlugin = {
  manifest: {
    id: 'wordpress',
    displayName: 'WordPress CMS',
    version: '6.4.3',
    documentRoot: 'public_html',
    defaultPackageUrl: 'https://wordpress.org/latest.zip',
    detectionMarkers: ['wp-config.php', 'wp-load.php'],
    requiredExtensions: ['mysqli', 'gd', 'curl', 'zip', 'xml'],
    main: 'index.ts',
  },

  async generateConfig(ctx: InstallContext): Promise<void> {
    const { webRoot, dbConfig, config } = ctx;
    const salts = [
      `define('AUTH_KEY',         '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('SECURE_AUTH_KEY',  '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('LOGGED_IN_KEY',    '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('NONCE_KEY',        '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('AUTH_SALT',        '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('SECURE_AUTH_SALT', '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('LOGGED_IN_SALT',   '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('NONCE_SALT',       '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
    ].join('\n');

    const wpConfigContent = `<?php
/**
 * The base configuration for WordPress
 *
 * Generated by WPHub managed hosting.
 */

define( 'DB_NAME', '${dbConfig.dbName}' );
define( 'DB_USER', '${dbConfig.dbUser}' );
define( 'DB_PASSWORD', '${dbConfig.dbPass}' );
define( 'DB_HOST', '${dbConfig.dbHost}:${dbConfig.dbPort}' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

${salts}

$table_prefix = '${dbConfig.dbPrefix || 'wp_'}';

define( 'WP_DEBUG', false );
$schema = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') ? 'https://' : 'http://';
$httpHost = $_SERVER['HTTP_HOST'] ?? '${config.domain}';
define( 'WP_SITEURL', $schema . $httpHost );
define( 'WP_HOME', $schema . $httpHost );

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
`;
    await fs.promises.writeFile(path.join(webRoot, 'wp-config.php'), wpConfigContent, 'utf8');
  },

  async executeInstall(ctx: InstallContext): Promise<void> {
    const { webRoot, config } = ctx;
    const phpExe = runtimeManager.getPhpCommand();
    const scriptPath = path.join(webRoot, 'wp-auto-install.php');
    
    const scriptContent = `<?php
define( 'WP_INSTALLING', true );
require_once __DIR__ . '/wp-load.php';
require_once ABSPATH . 'wp-admin/includes/upgrade.php';

$title = $argv[1] ?? 'My WordPress';
$user = $argv[2] ?? 'admin';
$email = $argv[3] ?? 'admin@example.com';
$password = $argv[4] ?? 'password';
$domain = $argv[5] ?? 'localhost';

$result = wp_install( $title, $user, $email, true, '', $password, 'en_US' );

$siteUrl = 'http://' . $domain;
update_option( 'siteurl', $siteUrl );
update_option( 'home', $siteUrl );
echo "INSTALL_SUCCESS";
`;

    await fs.promises.writeFile(scriptPath, scriptContent, 'utf8');

    const titleEsc = config.siteName.replace(/"/g, '\\"');
    const userEsc = config.adminUser.replace(/"/g, '\\"');
    const emailEsc = config.adminEmail.replace(/"/g, '\\"');
    const passEsc = config.adminPass.replace(/"/g, '\\"');
    const domainEsc = config.domain.replace(/"/g, '\\"');
    
    const cmd = `"${phpExe}" "${scriptPath}" "${titleEsc}" "${userEsc}" "${emailEsc}" "${passEsc}" "${domainEsc}"`;
    
    try {
      const { stdout, stderr } = await execPromise(cmd, { cwd: webRoot });
      await fs.promises.unlink(scriptPath).catch(() => {});
      
      if (!stdout.includes('INSTALL_SUCCESS')) {
        throw new Error(`WordPress wp_install execution returned: ${stdout}. Stderr: ${stderr}`);
      }
    } catch (err: any) {
      await fs.promises.unlink(scriptPath).catch(() => {});
      throw err;
    }
  },

  async verifyInstall(_ctx: InstallContext): Promise<boolean> {
    return true;
  },
};

export default wordpressPlugin;
