<?php
/**
 * The base configuration for WordPress
 *
 * Generated by WPHub managed hosting.
 */

define( 'DB_NAME', 'test' );
define( 'DB_USER', 'root' );
define( 'DB_PASSWORD', 'pass' );
define( 'DB_HOST', '127.0.0.1' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

define('AUTH_KEY',         '04y4os4eelxx7cpldd5tw0m');
define('SECURE_AUTH_KEY',  '66ttc0bhlt4it813oanfd');
define('LOGGED_IN_KEY',    '8l4kapx1opot1xaf8jxgyh');
define('NONCE_KEY',        'kvectlixorrz2jlmhukc2p');
define('AUTH_SALT',        'z8e3d1fkdtb3ozg09kcvry');
define('SECURE_AUTH_SALT', '7uq3fns2g195qom4b1k5ob');
define('LOGGED_IN_SALT',   'o7fjjbagre0glrksi7tf');
define('NONCE_SALT',       'fqa5oc304rrbptxvlj3cc5');

$table_prefix = 'wp_';

define( 'WP_DEBUG', false );
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
    $_SERVER['HTTPS'] = 'on';
}

$targetProto = 'https';
$schema = (
    (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') ||
    (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
) ? 'https://' : $targetProto . '://';

$httpHost = $_SERVER['HTTP_HOST'] ?? 'test-ssl-domain.wphub.cloud';
define( 'WP_SITEURL', $schema . $httpHost );
define( 'WP_HOME', $schema . $httpHost );

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
