import fs from 'fs';
import path from 'path';
import http from 'http';
import util from 'util';
import { exec } from 'child_process';
import { logger } from '@wphub/utils';
import { runtimeManager } from './runtimeManager';
import { InstallConfig } from './installerEngine';
import { cmsPluginLoader } from '../installers/pluginLoader';

const execPromise = util.promisify(exec);

export interface DatabaseConfig {
  dbName: string;
  dbUser: string;
  dbPass: string;
  dbHost: string;
  dbPort: number;
  dbPrefix?: string;
}

export interface CMSInstaller {
  slug: string;
  displayName: string;
  documentRoot: string;
  getDownloadUrl(version: string): string;
  preInstall(siteId: string, sitePath: string, webRoot: string, config: InstallConfig): Promise<void>;
  configure(webRoot: string, config: InstallConfig, db: DatabaseConfig): Promise<void>;
  install(webRoot: string, config: InstallConfig): Promise<void>;
  verify(port: number, webRoot: string, config: InstallConfig): Promise<boolean>;
  cleanup(webRoot: string, config: InstallConfig): Promise<void>;
  onRollback?(webRoot: string, config: InstallConfig, error: Error): Promise<void>;
}

// 1. WordPress Installer Plugin Module
export class WordPressInstaller implements CMSInstaller {
  slug = 'wordpress';
  displayName = 'WordPress';
  documentRoot = 'public_html';

  getDownloadUrl(_version: string): string {
    return 'https://wordpress.org/latest.zip';
  }

  async preInstall(_siteId: string, _sitePath: string, _webRoot: string, _config: InstallConfig): Promise<void> {}

  async configure(webRoot: string, config: InstallConfig, db: DatabaseConfig): Promise<void> {
    const salts = [
      `define('AUTH_KEY',         '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('SECURE_AUTH_KEY',  '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('LOGGED_IN_KEY',    '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('NONCE_KEY',        '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('AUTH_SALT',        '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('SECURE_AUTH_SALT', '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('LOGGED_IN_SALT',   '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
      `define('NONCE_SALT',       '${Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)}');`,
    ].join('\n');

    const wpConfigContent = `<?php
/**
 * The base configuration for WordPress
 *
 * Generated by WPHub managed hosting.
 */

define( 'DB_NAME', '${db.dbName}' );
define( 'DB_USER', '${db.dbUser}' );
define( 'DB_PASSWORD', '${db.dbPass}' );
define( 'DB_HOST', '${db.dbHost}:${db.dbPort}' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

${salts}

$table_prefix = '${db.dbPrefix || 'wp_'}';

define( 'WP_DEBUG', false );
define( 'WP_SITEURL', 'http://${config.domain}' );
define( 'WP_HOME', 'http://${config.domain}' );

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
`;
    await fs.promises.writeFile(path.join(webRoot, 'wp-config.php'), wpConfigContent, 'utf8');
  }

  async install(webRoot: string, config: InstallConfig): Promise<void> {
    const phpExe = runtimeManager.getPhpCommand();
    const scriptPath = path.join(webRoot, 'wp-auto-install.php');
    
    const scriptContent = `<?php
define( 'WP_INSTALLING', true );
require_once __DIR__ . '/wp-load.php';
require_once ABSPATH . 'wp-admin/includes/upgrade.php';

$title = $argv[1] ?? 'My WordPress';
$user = $argv[2] ?? 'admin';
$email = $argv[3] ?? 'admin@example.com';
$password = $argv[4] ?? 'password';

$result = wp_install( $title, $user, $email, true, '', $password, 'en_US' );
echo "INSTALL_SUCCESS";
`;

    await fs.promises.writeFile(scriptPath, scriptContent, 'utf8');

    const titleEsc = config.siteName.replace(/"/g, '\\"');
    const userEsc = config.adminUser.replace(/"/g, '\\"');
    const emailEsc = config.adminEmail.replace(/"/g, '\\"');
    const passEsc = config.adminPass.replace(/"/g, '\\"');
    
    const cmd = `"${phpExe}" "${scriptPath}" "${titleEsc}" "${userEsc}" "${emailEsc}" "${passEsc}"`;
    
    try {
      const { stdout, stderr } = await execPromise(cmd, { cwd: webRoot });
      await fs.promises.unlink(scriptPath).catch(() => {});
      
      if (!stdout.includes('INSTALL_SUCCESS')) {
        throw new Error(`WordPress wp_install execution returned: ${stdout}. Stderr: ${stderr}`);
      }
    } catch (err: any) {
      await fs.promises.unlink(scriptPath).catch(() => {});
      throw err;
    }
  }

  async verify(port: number, _webRoot: string, config: InstallConfig): Promise<boolean> {
    const dbName = config.dbName || 'wordpress_db';
    const prefix = config.dbPrefix || 'wp_';
    let tablesOk = false;
    for (let i = 0; i < 15; i++) {
      try {
        const stdout = await runtimeManager.runMariaDBQuery(`SHOW TABLES FROM \`${dbName}\` LIKE '${prefix}users';`);
        if (stdout.includes(`${prefix}users`)) {
          logger.info(`WordPress users table verified on check #${i + 1}`);
          tablesOk = true;
          break;
        }
      } catch (e: any) {
        // ignore errors
      }
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }

    if (!tablesOk) {
      logger.warn('WordPress table verification failed.');
      return false;
    }

    logger.info(`Performing login verification for user: ${config.adminUser} on port ${port}...`);
    return new Promise((resolve) => {
      const postData = `log=${encodeURIComponent(config.adminUser)}&pwd=${encodeURIComponent(config.adminPass)}&wp-submit=Log+In`;
      
      const options = {
        hostname: '127.0.0.1',
        port: port,
        path: '/wp-login.php',
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'Content-Length': Buffer.byteLength(postData),
        },
      };

      const req = http.request(options, (res) => {
        if (res.statusCode === 302 || (res.headers.location && res.headers.location.includes('wp-admin'))) {
          logger.info('WordPress admin login health check verified successfully (HTTP 302 Redirect).');
          resolve(true);
        } else {
          logger.warn(`WordPress admin login health check failed with status: ${res.statusCode}`);
          resolve(false);
        }
      });

      req.on('error', (err) => {
        logger.error(`WordPress login health check request error: ${err.message}`);
        resolve(false);
      });

      req.write(postData);
      req.end();
    });
  }

  async cleanup(_webRoot: string, _config: InstallConfig): Promise<void> {}
}

// 2. Laravel Installer Plugin Module
export class LaravelInstaller implements CMSInstaller {
  slug = 'laravel';
  displayName = 'Laravel';
  documentRoot = 'public';

  getDownloadUrl(_version: string): string {
    return 'https://github.com/laravel/laravel/archive/refs/heads/10.x.zip';
  }

  async preInstall(_siteId: string, _sitePath: string, _webRoot: string, _config: InstallConfig): Promise<void> {}

  async configure(webRoot: string, config: InstallConfig, db: DatabaseConfig): Promise<void> {
    const envContent = `APP_NAME="${config.siteName}"
APP_ENV=local
APP_KEY=base64:${Buffer.from(Math.random().toString()).toString('base64')}
APP_DEBUG=true
APP_URL=http://${config.domain}

DB_CONNECTION=mysql
DB_HOST=${db.dbHost}
DB_PORT=${db.dbPort}
DB_DATABASE=${db.dbName}
DB_USERNAME=${db.dbUser}
DB_PASSWORD=${db.dbPass}
`;
    await fs.promises.writeFile(path.join(webRoot, '..', '.env'), envContent, 'utf8');
  }

  async install(_webRoot: string, _config: InstallConfig): Promise<void> {}

  async verify(_port: number, _webRoot: string, _config: InstallConfig): Promise<boolean> {
    return true;
  }

  async cleanup(_webRoot: string, _config: InstallConfig): Promise<void> {}
}

// 3. Joomla Installer Plugin Module
export class JoomlaInstaller implements CMSInstaller {
  slug = 'joomla';
  displayName = 'Joomla';
  documentRoot = 'public_html';

  getDownloadUrl(_version: string): string {
    return 'https://github.com/joomla/joomla-cms/releases/download/5.0.3/Joomla_5.0.3-Stable-Full_Package.zip';
  }

  async preInstall(_siteId: string, _sitePath: string, _webRoot: string, _config: InstallConfig): Promise<void> {}

  async configure(webRoot: string, config: InstallConfig, db: DatabaseConfig): Promise<void> {
    const joomlaConfig = `<?php
class JConfig {
	public $dbtype = 'mysqli';
	public $host = '${db.dbHost}';
	public $user = '${db.dbUser}';
	public $password = '${db.dbPass}';
	public $db = '${db.dbName}';
	public $dbprefix = '${db.dbPrefix || 'joom_'}';
	public $sitename = '${config.siteName}';
}
`;
    await fs.promises.writeFile(path.join(webRoot, 'configuration.php'), joomlaConfig, 'utf8');
  }

  async install(_webRoot: string, _config: InstallConfig): Promise<void> {}

  async verify(_port: number, _webRoot: string, _config: InstallConfig): Promise<boolean> {
    return true;
  }

  async cleanup(_webRoot: string, _config: InstallConfig): Promise<void> {}
}

// 4. Drupal Installer Plugin Module
export class DrupalInstaller implements CMSInstaller {
  slug = 'drupal';
  displayName = 'Drupal';
  documentRoot = 'web';

  getDownloadUrl(_version: string): string {
    return 'https://www.drupal.org/download-latest/zip';
  }

  async preInstall(_siteId: string, _sitePath: string, _webRoot: string, _config: InstallConfig): Promise<void> {}

  async configure(_webRoot: string, _config: InstallConfig, _db: DatabaseConfig): Promise<void> {}

  async install(_webRoot: string, _config: InstallConfig): Promise<void> {}

  async verify(_port: number, _webRoot: string, _config: InstallConfig): Promise<boolean> {
    return true;
  }

  async cleanup(_webRoot: string, _config: InstallConfig): Promise<void> {}
}

// 5. Ghost Installer Plugin Module
export class GhostInstaller implements CMSInstaller {
  slug = 'ghost';
  displayName = 'Ghost';
  documentRoot = '';

  getDownloadUrl(_version: string): string {
    return 'https://github.com/TryGhost/Ghost/archive/refs/tags/v5.75.0.zip';
  }

  async preInstall(_siteId: string, _sitePath: string, _webRoot: string, _config: InstallConfig): Promise<void> {}

  async configure(webRoot: string, config: InstallConfig, db: DatabaseConfig): Promise<void> {
    const ghostConfig = {
      url: `http://${config.domain}`,
      server: { port: 2368, host: '127.0.0.1' },
      database: {
        client: 'mysql',
        connection: {
          host: db.dbHost,
          port: db.dbPort,
          user: db.dbUser,
          password: db.dbPass,
          database: db.dbName
        }
      }
    };
    await fs.promises.writeFile(
      path.join(webRoot, 'config.production.json'),
      JSON.stringify(ghostConfig, null, 2),
      'utf8'
    );
  }

  async install(_webRoot: string, _config: InstallConfig): Promise<void> {}

  async verify(_port: number, _webRoot: string, _config: InstallConfig): Promise<boolean> {
    return true;
  }

  async cleanup(_webRoot: string, _config: InstallConfig): Promise<void> {}
}

// 6. Magento Installer Plugin Module
export class MagentoInstaller implements CMSInstaller {
  slug = 'magento';
  displayName = 'Magento';
  documentRoot = '';

  getDownloadUrl(_version: string): string {
    return 'https://github.com/magento/magento2/archive/refs/tags/2.4.6.zip';
  }

  async preInstall(_siteId: string, _sitePath: string, _webRoot: string, _config: InstallConfig): Promise<void> {}

  async configure(_webRoot: string, _config: InstallConfig, _db: DatabaseConfig): Promise<void> {}

  async install(_webRoot: string, _config: InstallConfig): Promise<void> {}

  async verify(_port: number, _webRoot: string, _config: InstallConfig): Promise<boolean> {
    return true;
  }

  async cleanup(_webRoot: string, _config: InstallConfig): Promise<void> {}
}

// 7. Generic Fallback Installer Module
export class GenericCMSInstaller implements CMSInstaller {
  slug = 'generic';
  displayName = 'Generic CMS';
  documentRoot = '';

  constructor(appSlug: string) {
    this.slug = appSlug;
    this.displayName = appSlug.charAt(0).toUpperCase() + appSlug.slice(1);
  }

  getDownloadUrl(_version: string): string {
    const urls: Record<string, string> = {
      prestashop: 'https://github.com/PrestaShop/PrestaShop/releases/download/8.1.3/prestashop_8.1.3.zip',
      magento: 'https://github.com/magento/magento2/archive/refs/tags/2.4.6.zip',
    };
    return urls[this.slug.toLowerCase()] || `https://github.com/${this.slug}/${this.slug}/archive/refs/heads/main.zip`;
  }

  async preInstall(_siteId: string, _sitePath: string, _webRoot: string, _config: InstallConfig): Promise<void> {}

  async configure(_webRoot: string, _config: InstallConfig, _db: DatabaseConfig): Promise<void> {}

  async install(_webRoot: string, _config: InstallConfig): Promise<void> {}

  async verify(_port: number, _webRoot: string, _config: InstallConfig): Promise<boolean> {
    return true;
  }

  async cleanup(_webRoot: string, _config: InstallConfig): Promise<void> {}
}

// 8. Installer Module Registry
class InstallerRegistry {
  private installers = new Map<string, CMSInstaller>();

  constructor() {
    this.register(new WordPressInstaller());
    this.register(new LaravelInstaller());
    this.register(new JoomlaInstaller());
    this.register(new DrupalInstaller());
    this.register(new GhostInstaller());
    this.register(new MagentoInstaller());
    
    // Discover external dropped-in installer modules asynchronously
    cmsPluginLoader.discoverAndLoadModules().catch((err) => {
      logger.error(`Dynamic CMS module discovery error: ${err.message}`);
    });
  }

  register(installer: CMSInstaller) {
    this.installers.set(installer.slug.toLowerCase(), installer);
  }

  get(slug: string): CMSInstaller {
    const normSlug = slug.toLowerCase();
    if (this.installers.has(normSlug)) {
      return this.installers.get(normSlug)!;
    }
    
    // Check dynamic plugin loader for dropped-in modules
    try {
      const plugin = cmsPluginLoader.getModule(normSlug);
      if (plugin && plugin.manifest) {
        return {
          slug: plugin.manifest.id,
          displayName: plugin.manifest.displayName,
          documentRoot: plugin.manifest.documentRoot,
          getDownloadUrl: (_ver: string) => plugin.manifest.defaultPackageUrl,
          preInstall: async (siteId, sitePath, webRoot, config) => {
            if (plugin.preInstall) {
              await plugin.preInstall({ siteId, domain: config.domain, sitePath, webRoot, dbConfig: { dbName: '', dbUser: '', dbPass: '', dbHost: '', dbPort: 3306 }, config });
            }
          },
          configure: async (webRoot, config, dbConfig) => {
            if (plugin.generateConfig) {
              await plugin.generateConfig({ siteId: config.siteId, domain: config.domain, sitePath: webRoot, webRoot, dbConfig, config });
            }
          },
          install: async (webRoot, config) => {
            if (plugin.executeInstall) {
              await plugin.executeInstall({ siteId: config.siteId, domain: config.domain, sitePath: webRoot, webRoot, dbConfig: { dbName: '', dbUser: '', dbPass: '', dbHost: '', dbPort: 3306 }, config });
            }
          },
          verify: async (_port, webRoot, config) => {
            if (plugin.verifyInstall) {
              return await plugin.verifyInstall({ siteId: config.siteId, domain: config.domain, sitePath: webRoot, webRoot, dbConfig: { dbName: '', dbUser: '', dbPass: '', dbHost: '', dbPort: 3306 }, config });
            }
            return true;
          },
          cleanup: async (webRoot, config) => {
            if (plugin.cleanup) {
              await plugin.cleanup({ siteId: config.siteId, domain: config.domain, sitePath: webRoot, webRoot, dbConfig: { dbName: '', dbUser: '', dbPass: '', dbHost: '', dbPort: 3306 }, config });
            }
          },
          onRollback: async (webRoot, config, err) => {
            if (plugin.onRollback) {
              await plugin.onRollback({ siteId: config.siteId, domain: config.domain, sitePath: webRoot, webRoot, dbConfig: { dbName: '', dbUser: '', dbPass: '', dbHost: '', dbPort: 3306 }, config }, err);
            }
          },
        };
      }
    } catch (_err) {
      // ignore
    }

    return new GenericCMSInstaller(normSlug);
  }
}

export const installerRegistry = new InstallerRegistry();
